version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test
  
  build-and-push:
    executor: docker/docker    
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: edisonzsq/education-space
          tag: <<pipeline.git.tag>>
      - docker/push:
          image: edisonzsq/education-space
          tag: <<pipeline.git.tag>>

  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - docker/check
      - run: |
          echo "Pull image from docker.io registry"
          docker pull edisonzsq/education-space:<<pipeline.git.tag>>  
      - heroku/install
      - run: |
          echo "Deploy docker image to heroku"
          heroku container:login
          docker tag edisonzsq/education-space:<<pipeline.git.tag>> registry.heroku.com/edison-su-devops
          echo "Push image to heroku registry"
          docker push registry.heroku.com/edison-su-devops
          echo "Heroku release"
          heroku container:release web -a edison-su-devops

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build 
          filters:
            branches:
              only: main     
      - build-and-push:  
          filters:
            tags:
              only: /^v.*/  
            branches: 
              ignore: /.*/
      - deploy:
          requires:
            - build-and-push
          filters:
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/
